/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculadora;

/**
 *
 * @author Fran
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTResultado = new javax.swing.JTextField();
        jB07 = new javax.swing.JButton();
        jB08 = new javax.swing.JButton();
        jB09 = new javax.swing.JButton();
        jB04 = new javax.swing.JButton();
        jB05 = new javax.swing.JButton();
        jB06 = new javax.swing.JButton();
        jB01 = new javax.swing.JButton();
        jB02 = new javax.swing.JButton();
        jB03 = new javax.swing.JButton();
        jB0 = new javax.swing.JButton();
        jBComa = new javax.swing.JButton();
        jBBin = new javax.swing.JButton();
        jBSumar = new javax.swing.JButton();
        jBRestar = new javax.swing.JButton();
        jBMultiplicar = new javax.swing.JButton();
        jBDividir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTResultado.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTResultadoActionPerformed(evt);
            }
        });

        jB07.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB07.setText("7");
        jB07.setPreferredSize(new java.awt.Dimension(50, 50));
        jB07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB07ActionPerformed(evt);
            }
        });

        jB08.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB08.setText("8");
        jB08.setPreferredSize(new java.awt.Dimension(50, 50));
        jB08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB08ActionPerformed(evt);
            }
        });

        jB09.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB09.setText("9");
        jB09.setPreferredSize(new java.awt.Dimension(50, 50));
        jB09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB09ActionPerformed(evt);
            }
        });

        jB04.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB04.setText("4");
        jB04.setPreferredSize(new java.awt.Dimension(50, 50));
        jB04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB04ActionPerformed(evt);
            }
        });

        jB05.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB05.setText("5");
        jB05.setPreferredSize(new java.awt.Dimension(50, 50));
        jB05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB05ActionPerformed(evt);
            }
        });

        jB06.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB06.setText("6");
        jB06.setPreferredSize(new java.awt.Dimension(50, 50));
        jB06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB06ActionPerformed(evt);
            }
        });

        jB01.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB01.setText("1");
        jB01.setPreferredSize(new java.awt.Dimension(50, 50));
        jB01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB01ActionPerformed(evt);
            }
        });

        jB02.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB02.setText("2");
        jB02.setPreferredSize(new java.awt.Dimension(50, 50));
        jB02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB02ActionPerformed(evt);
            }
        });

        jB03.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB03.setText("3");
        jB03.setPreferredSize(new java.awt.Dimension(50, 50));
        jB03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB03ActionPerformed(evt);
            }
        });

        jB0.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB0.setText("0");
        jB0.setPreferredSize(new java.awt.Dimension(50, 50));
        jB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB0ActionPerformed(evt);
            }
        });

        jBComa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBComa.setText(",");
        jBComa.setPreferredSize(new java.awt.Dimension(50, 50));
        jBComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBComaActionPerformed(evt);
            }
        });

        jBBin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBBin.setText("BIN");

        jBSumar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBSumar.setText("+");

        jBRestar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBRestar.setText("/");

        jBMultiplicar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBMultiplicar.setText("*");

        jBDividir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBDividir.setText("-");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("=");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("CE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jB04, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jB07, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jB01, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jB05, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jB02, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jB08, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jB09, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(jB06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jB03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBBin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jB0, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBComa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jTResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB06, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB01, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB02, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBComa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBBin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 181, Short.MAX_VALUE))
        );

        jB08.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTResultadoActionPerformed

    private void jB07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB07ActionPerformed
        //Este metodo captura un click
        //jTResultado.setText("7");

        String antes = jTResultado.getText();
        if (antes.equalsIgnoreCase("0")){
            jTResultado.setText(antes + "7");
        }else{
            jTResultado.setText(antes + "7");
        }
    }//GEN-LAST:event_jB07ActionPerformed

    private void jB0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB0ActionPerformed
        String antes = jTResultado.getText();
        if (antes.equalsIgnoreCase("0")){
            jTResultado.setText(antes + "0");
        }else{
            jTResultado.setText(antes + "0");
        }
    }//GEN-LAST:event_jB0ActionPerformed

    private void jBComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBComaActionPerformed
        String antes = jTResultado.getText();
        if (antes.equalsIgnoreCase("0")){
            jTResultado.setText(antes + "#");
        }else{
            jTResultado.setText(antes + "#");
        }
    }//GEN-LAST:event_jBComaActionPerformed

    private void jB03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB03ActionPerformed
        String antes = jTResultado.getText();
        if (antes.equalsIgnoreCase("0")){
            jTResultado.setText(antes + "3");
        }else{
            jTResultado.setText(antes + "3");
        }
    }//GEN-LAST:event_jB03ActionPerformed

    private void jB02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB02ActionPerformed
        String antes = jTResultado.getText();
        if (antes.equalsIgnoreCase("0")){
            jTResultado.setText(antes + "2");
        }else{
            jTResultado.setText(antes + "2");
        }
    }//GEN-LAST:event_jB02ActionPerformed

    private void jB01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB01ActionPerformed
        String antes = jTResultado.getText();
        if (antes.equalsIgnoreCase("0")){
            jTResultado.setText(antes + "1");
        }else{
            jTResultado.setText(antes + "1");
        }
    }//GEN-LAST:event_jB01ActionPerformed

    private void jB06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB06ActionPerformed
        String antes = jTResultado.getText();
        if (antes.equalsIgnoreCase("0")){
            jTResultado.setText(antes + "6");
        }else{
            jTResultado.setText(antes + "6");
        }
    }//GEN-LAST:event_jB06ActionPerformed

    private void jB05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB05ActionPerformed
        String antes = jTResultado.getText();
        if (antes.equalsIgnoreCase("0")){
            jTResultado.setText(antes + "5");
        }else{
            jTResultado.setText(antes + "5");
        }
    }//GEN-LAST:event_jB05ActionPerformed

    private void jB04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB04ActionPerformed
        String antes = jTResultado.getText();
        if (antes.equalsIgnoreCase("0")){
            jTResultado.setText(antes + "4");
        }else{
            jTResultado.setText(antes + "4");
        }
    }//GEN-LAST:event_jB04ActionPerformed

    private void jB08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB08ActionPerformed
        String antes = jTResultado.getText();
        if (antes.equalsIgnoreCase("0")){
            jTResultado.setText(antes + "8");
        }else{
            jTResultado.setText(antes + "8");
        }
    }//GEN-LAST:event_jB08ActionPerformed

    private void jB09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB09ActionPerformed
        String antes = jTResultado.getText();
        if (antes.equalsIgnoreCase("0")){
            jTResultado.setText(antes + "9");
        }else{
            jTResultado.setText(antes + "9");
        }
    }//GEN-LAST:event_jB09ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB0;
    private javax.swing.JButton jB01;
    private javax.swing.JButton jB02;
    private javax.swing.JButton jB03;
    private javax.swing.JButton jB04;
    private javax.swing.JButton jB05;
    private javax.swing.JButton jB06;
    private javax.swing.JButton jB07;
    private javax.swing.JButton jB08;
    private javax.swing.JButton jB09;
    private javax.swing.JButton jBBin;
    private javax.swing.JButton jBComa;
    private javax.swing.JButton jBDividir;
    private javax.swing.JButton jBMultiplicar;
    private javax.swing.JButton jBRestar;
    private javax.swing.JButton jBSumar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jTResultado;
    // End of variables declaration//GEN-END:variables
}
